Document: c-functools
Title: Debian c-functools Manual
Author: <insert document author here>
Abstract: This manual describes what c-functools is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/c-functools/c-functools.sgml.gz

Format: postscript
Files: /usr/share/doc/c-functools/c-functools.ps.gz

Format: text
Files: /usr/share/doc/c-functools/c-functools.text.gz

Format: HTML
Index: /usr/share/doc/c-functools/html/index.html
Files: /usr/share/doc/c-functools/html/*.html
